const KEY="dividir-conta-v2",DEFAULT={events:[],active:null};let db=JSON.parse(localStorage.getItem(KEY)||"null")||DEFAULT;let splitMode="equal";
const $=id=>document.getElementById(id),today=()=>new Date().toISOString().slice(0,10),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function current(){return db.events.find(e=>e.id===db.active)||db.events[0]}
function money(v){let e=current();return new Intl.NumberFormat("pt-BR",{style:"currency",currency:e?.currency||"BRL"}).format(Number(v)||0)}
function persist(){localStorage.setItem(KEY,JSON.stringify(db));render()}
function newEvent(){let e={id:crypto.randomUUID(),name:"Novo evento",currency:"BRL",people:[],expenses:[],payments:[],createdAt:Date.now()};db.events.push(e);db.active=e.id;persist()}
function init(){if(!db.events.length)newEvent();else{if(!db.active||!current())db.active=db.events[0].id;render()}}
function render(){let e=current();if(!e)return;renderEvents();$("eventName").value=e.name;$("currency").value=e.currency;renderPeople();renderPayer();renderSplit();renderExpenses();renderBalances();renderStats();renderSettlements();renderPayments()}
function renderEvents(){$("eventSelect").innerHTML=db.events.map(e=>'<option value="'+e.id+'" '+(e.id===db.active?"selected":"")+'>'+esc(e.name||"Sem nome")+"</option>").join("")}
function renderPeople(){let e=current();$("people").innerHTML=e.people.length?e.people.map((p,i)=>'<span class="chip">'+esc(p)+' <button title="Renomear" onclick="renamePerson('+i+')">✎</button><button title="Remover" onclick="removePerson('+i+')">×</button></span>').join(""):'<span class="muted">Adicione as pessoas que participarão.</span>'}
function renderPayer(){let e=current();$("expensePayer").innerHTML=e.people.map(p=>'<option>'+esc(p)+'</option>').join("")}
function renderSplit(){let e=current();if(splitMode==="equal"){$("splitEqual").innerHTML=e.people.length?e.people.map(p=>'<label style="display:flex;flex-direction:row;align-items:center;margin:7px 0;font-weight:500"><input class="split-check" type="checkbox" value="'+esc(p)+'" checked style="width:auto;margin-right:8px">'+esc(p)+'</label>').join(""):'<div class="empty">Adicione participantes primeiro.</div>';$("splitCustom").classList.add("hidden");$("splitEqual").classList.remove("hidden")}else{$("splitCustom").classList.remove("hidden");$("splitEqual").classList.add("hidden");$("splitCustom").innerHTML=e.people.length?e.people.map(p=>'<div class="custom-row"><div class="chip">'+esc(p)+'</div><input class="custom-value" data-person="'+esc(p)+'" type="number" min="0" step="0.01" placeholder="0,00"></div>').join(""):'<div class="empty">Adicione participantes primeiro.</div>'}}
function renderExpenses(){let e=current(),el=$("expenses");if(!e.expenses.length){el.innerHTML='<div class="empty">Nenhuma despesa adicionada.</div>';return}el.innerHTML=e.expenses.slice().reverse().map((x,ri)=>{let i=e.expenses.length-1-ri;return '<div class="expense"><div><strong>'+esc(x.desc)+'</strong><br><small>'+esc(x.payer)+' pagou · '+esc(x.date)+' · '+x.shares.length+' pessoa(s)</small></div><div style="text-align:right"><strong>'+money(x.amount)+'</strong><br><button class="small" onclick="editExpense('+i+')">✎</button> <button class="small danger" onclick="removeExpense('+i+')">Excluir</button></div></div>'}).join("")}
function rawBalances(){let e=current(),b=Object.fromEntries(e.people.map(p=>[p,0]));e.expenses.forEach(x=>{b[x.payer]=(b[x.payer]||0)+Number(x.amount);x.shares.forEach(s=>b[s.person]=(b[s.person]||0)-Number(s.amount))});return b}
function netBalances(){let b=rawBalances();current().payments.forEach(p=>{b[p.from]=(b[p.from]||0)+Number(p.amount);b[p.to]=(b[p.to]||0)-Number(p.amount)});return b}
function renderBalances(){let b=netBalances(),e=current();$("balances").innerHTML=e.people.length?e.people.map(p=>'<div class="balance"><span>'+esc(p)+'</span><strong class="'+(b[p]>=-0.005?"positive":"negative")+'">'+(b[p]>=-0.005?"+":"")+money(b[p])+'</strong></div>').join(""):'<div class="empty">Adicione participantes.</div>'}
function suggestions(){let b=netBalances(),cred=Object.entries(b).filter(([,v])=>v>.005).map(([p,v])=>({p,v})).sort((a,z)=>z.v-a.v),debt=Object.entries(b).filter(([,v])=>v<-.005).map(([p,v])=>({p,v:-v})).sort((a,z)=>z.v-a.v),out=[];let i=0,j=0;while(i<cred.length&&j<debt.length){let n=Math.min(cred[i].v,debt[j].v);out.push({from:debt[j].p,to:cred[i].p,value:Math.round(n*100)/100});cred[i].v-=n;debt[j].v-=n;if(cred[i].v<.005)i++;if(debt[j].v<.005)j++}return out}
function renderSettlements(){let out=suggestions();$("settlements").innerHTML=out.length?out.map((x,i)=>'<div class="settle"><span><strong>'+esc(x.from)+'</strong> paga <strong>'+esc(x.to)+'</strong></span><span><strong>'+money(x.value)+'</strong> <button class="small" onclick="markPaid('+i+')">✓ Paguei</button></span></div>').join(""):'<div class="empty">Tudo quitado. Ninguém precisa pagar ninguém.</div>'}
function renderPayments(){let e=current();$("payments").innerHTML=e.payments.length?e.payments.slice().reverse().map(p=>'<div class="payment"><span>✓ '+esc(p.from)+' pagou '+esc(p.to)+' <span class="date">· '+esc(p.date)+'</span></span><span><strong>'+money(p.amount)+'</strong> <button class="small" onclick="undoPayment(\''+p.id+'\')">Desfazer</button></span></div>').join(""):'<div class="empty">Nenhum pagamento registrado.</div>'}
function renderStats(){let e=current();$("total").textContent=money(e.expenses.reduce((a,x)=>a+Number(x.amount),0));$("expenseCount").textContent=e.expenses.length;$("personCount").textContent=e.people.length}
function addPerson(){let e=current(),n=$("personName").value.trim();if(!n)return;if(e.people.some(p=>p.toLowerCase()===n.toLowerCase()))return alert("Essa pessoa já foi adicionada.");e.people.push(n);$("personName").value="";persist()}
function renamePerson(i){let e=current(),old=e.people[i],n=prompt("Novo nome:",old)?.trim();if(!n||n===old)return;if(e.people.some((p,j)=>j!==i&&p.toLowerCase()===n.toLowerCase()))return alert("Essa pessoa já existe.");e.people[i]=n;e.expenses.forEach(x=>{if(x.payer===old)x.payer=n;x.shares.forEach(s=>{if(s.person===old)s.person=n})});e.payments.forEach(p=>{if(p.from===old)p.from=n;if(p.to===old)p.to=n});persist()}
function removePerson(i){let e=current(),p=e.people[i];if(e.expenses.some(x=>x.payer===p||x.shares.some(s=>s.person===p))||e.payments.some(x=>x.from===p||x.to===p))return alert("Essa pessoa já está envolvida em movimentações e não pode ser removida.");e.people.splice(i,1);persist()}
function collectShares(amount){let e=current(),shares=[];if(splitMode==="equal"){let ps=[...document.querySelectorAll(".split-check:checked")].map(x=>x.value);if(!ps.length)throw Error("Selecione ao menos uma pessoa.");let cents=Math.round(amount*100),base=Math.floor(cents/ps.length),rest=cents%ps.length;shares=ps.map((p,i)=>({person:p,amount:(base+(i<rest?1:0))/100}))}else{shares=[...document.querySelectorAll(".custom-value")].map(x=>({person:x.dataset.person,amount:Number(x.value)||0})).filter(x=>x.amount>0);let sum=shares.reduce((a,x)=>a+x.amount,0);if(Math.abs(sum-amount)>.005)throw Error("A soma das divisões deve ser igual ao valor da despesa.");if(!shares.length)throw Error("Informe as partes da despesa.")}return shares}
function addExpense(){let e=current(),desc=$("expenseDesc").value.trim(),amount=Number($("expenseAmount").value),payer=$("expensePayer").value,date=$("expenseDate").value||today();if(!desc||!amount||amount<=0||!payer)return alert("Preencha descrição, valor e quem pagou.");try{e.expenses.push({id:crypto.randomUUID(),desc,amount,payer,date,shares:collectShares(amount)});$("expenseDesc").value="";$("expenseAmount").value="";persist()}catch(err){alert(err.message)}}
function editExpense(i){let e=current(),x=e.expenses[i],desc=prompt("Descrição:",x.desc);if(desc===null)return;let amount=Number(prompt("Valor:",x.amount));if(!amount||amount<=0)return alert("Valor inválido.");let payer=prompt("Quem pagou?\n"+e.people.join(", "),x.payer);if(!payer||!e.people.includes(payer))return alert("Pagador inválido.");let date=prompt("Data (AAAA-MM-DD):",x.date)||x.date;let parts=prompt("Dividir igualmente entre (separe por vírgula):",x.shares.map(s=>s.person).join(", "));if(parts===null)return;let ps=parts.split(",").map(s=>s.trim()).filter(Boolean);if(!ps.length||ps.some(p=>!e.people.includes(p)))return alert("Participante inválido.");let cents=Math.round(amount*100),base=Math.floor(cents/ps.length),rest=cents%ps.length;x.desc=desc.trim();x.amount=amount;x.payer=payer;x.date=date;x.shares=ps.map((p,k)=>({person:p,amount:(base+(k<rest?1:0))/100}));persist()}
function removeExpense(i){if(confirm("Excluir esta despesa?")){current().expenses.splice(i,1);persist()}}
function markPaid(i){let s=suggestions()[i];if(!s)return;current().payments.push({id:crypto.randomUUID(),from:s.from,to:s.to,amount:s.value,date:today()});persist()}
function undoPayment(id){current().payments=current().payments.filter(p=>p.id!==id);persist()}
function deleteEvent(){if(db.events.length===1)return alert("Mantenha pelo menos um evento.");if(!confirm("Excluir este evento e todas as suas despesas?"))return;db.events=db.events.filter(e=>e.id!==db.active);db.active=db.events[0].id;persist()}
function exportData(){let e=current(),data={evento:e.name,moeda:e.currency,participantes:e.people,despesas:e.expenses,pagamentos:e.payments,saldos:netBalances()};let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download=(e.name||"dividir-conta").replace(/[^a-z0-9]+/gi,"-").toLowerCase()+".json";a.click();URL.revokeObjectURL(a.href)}
async function share(){let e=current(),text="Dividir Conta — "+e.name+"\nTotal: "+money(e.expenses.reduce((a,x)=>a+x.amount,0))+"\n\n"+suggestions().map(s=>s.from+" paga "+s.to+" "+money(s.value)).join("\n");if(navigator.share){try{await navigator.share({title:e.name,text})}catch{}}else{await navigator.clipboard?.writeText(text);alert("Resumo copiado para a área de transferência.")}}
function settleAll(){let out=suggestions();if(!out.length)return alert("Não há acertos pendentes.");if(!confirm("Registrar todos os acertos sugeridos como pagos?"))return;let e=current();out.forEach(s=>e.payments.push({id:crypto.randomUUID(),from:s.from,to:s.to,amount:s.value,date:today()}));persist()}
$("eventSelect").onchange=e=>{db.active=e.target.value;persist()};$("newEvent").onclick=newEvent;$("deleteEvent").onclick=deleteEvent;$("addPerson").onclick=addPerson;$("personName").onkeydown=e=>{if(e.key==="Enter")addPerson()};$("addExpense").onclick=addExpense;$("clearExpenses").onclick=()=>{if(confirm("Apagar todas as despesas deste evento?")){current().expenses=[];current().payments=[];persist()}};$("eventName").oninput=e=>{current().name=e.target.value;localStorage.setItem(KEY,JSON.stringify(db));renderEvents()};$("currency").onchange=e=>{current().currency=e.target.value;persist()};$("exportBtn").onclick=exportData;$("shareBtn").onclick=share;$("settleAll").onclick=settleAll;document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{splitMode=b.dataset.mode;document.querySelectorAll("[data-mode]").forEach(x=>x.classList.toggle("active",x===b));renderSplit()});init();